using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;

namespace WebApplication1
{
    public class Global : System.Web.HttpApplication
    {

        protected void Application_Start(object sender, EventArgs e)
        {
            Application["userList"] = new List<user>();
            Application["listMovie"] = new List<movie>();

            //tạo user admin
            List<user> users = new List<user>();
            List<MovieTicket> movieTickets = new List<MovieTicket>();
            users.Add(new user("admin", "admin@gmail.com", "admin123", movieTickets));
            Application["userList"] = users;



            //thêm dữ liệu vào movie
            List<movie> movies = new List<movie>();

            movies.Add(new movie(1, "Đông cung", "Đông cung", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 50, 2002, "Hành động", "assets/images/product-all/DongCung1.jpg", 20000));
            movies.Add(new movie(2, "Hộc châu phu nhân", "Hộc châu phu nhân", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 60, 2002, "Hành động", "assets/images/product-all/HocChauPhuNhan4.jpg", 120000));
            movies.Add(new movie(3, "Hương mật tựa khói sương", "Hương mật tựa khói sương", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 70, 2002, "Hành động", "assets/images/product-all/HuongMatTuaKhoiSuong5.jpg", 100000));
            movies.Add(new movie(4, "Khánh dư niên", "Khánh dư niên", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 80, 2002, "Hành động", "assets/images/product-all/KhanhDuNien3.jpg", 100000));
            movies.Add(new movie(5, "Luận anh hùng", "Luận anh hùng", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 100, 2002, "Hành động", "assets/images/product-all/DongCung1.jpg", 250000));
            movies.Add(new movie(6, "Lưu ly mỹ nhân sát", "Lưu ly mỹ nhân sát", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 110, 2002, "Hành động", "assets/images/product-all/LuuLyMyNhanSat1.jpg", 90000));
            movies.Add(new movie(7, "Mộ nam chi", "Mộ nam chi", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 120, 2002, "Hành động", "assets/images/product-all/MoNamChi1.jpg", 65000));
            movies.Add(new movie(8, "Mộng hoa lục", "Mộng hoa lục", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 130, 2002, "Hành động", "assets/images/product-all/MongHoaLuc5.jpg", 86000));
            movies.Add(new movie(9, "Ngộ long", "Ngộ long", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 140, 2002, "Hành động", "assets/images/product-all/NgoLong1.jpg", 100000));
            movies.Add(new movie(10, "Nhất kiến khuynh tâm", "Nhất kiến khuynh tâm", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 150, 2002, "Hành động", "assets/images/product-all/NhatKienKhuynhTam5.jpg", 54000));
            movies.Add(new movie(11, "Phư ý phương phi", "Phư ý phương phi", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 160, 2002, "Hành động", "assets/images/product-all/NhuYPhuongPhi1.jpg", 120000));
            movies.Add(new movie(12, "Phù thế song kiều truyện", "Phù thế song kiều truyện", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 155, 2002, "Hành động", "assets/images/product-all/PhuTheSongKieuTruyen1.jpg", 150000));
            movies.Add(new movie(13, "Sơn hà lệnh", "Sơn hà lệnh", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 145, 2002, "Hành động", "assets/images/product-all/SonHaLenh4.jpg", 150000));
            movies.Add(new movie(14, "Thiên kim háo sắc", "Thiên kim háo sắc", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 135, 2002, "Hành động", "assets/images/product-all/ThienKimHaoSac3.jpg", 60000));
            movies.Add(new movie(15, "Tranh thiên hạ", "Tranh thiên hạ", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 125, 2002, "Hành động", "assets/images/product-all/TranhThienHa1.jpg", 40000));
            movies.Add(new movie(16, "Trần tình lệnh", "Trần tình lệnh", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 115, 2002, "Hành động", "assets/images/product-all/TranTinhLenh5.jpg", 60000));
            movies.Add(new movie(17, "Tuyết trung hãn đạo hành", "Tuyết trung hãn đạo hành", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 105, 2002, "Hành động", "assets/images/product-all/TuyetTrungHanDaoHanh6.jpg", 20000));
            movies.Add(new movie(18, "Ỷ thiên đồ long ký", "Ỷ thiên đồ long ký", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 95, 2002, "Hành động", "assets/images/product-all/YThienDoLongKy1.jpg", 20000));
            movies.Add(new movie(19, "Bạch phát vương phi", "Bạch phát vương phi", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 85, 2002, "Hành động", "assets/images/product-all/BachPhatVuongPhi1.jpg", 20000));
            movies.Add(new movie(20, "Đầu phá thương khung", "Đầu phá thương khung", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci? Laboriosam ducimus dolores temporibus est eius beatae molestiae tempore eum officia reprehenderit, nulla possimus doloribus libero nisi illum mollitia atque. Labore ad aliquid eos dolorem nihil excepturi sit sapiente quod neque obcaecati, iure id cupiditate eligendi, sequi praesentium sint deserunt quaerat est eveniet. Eos odio, ipsum nobis debitis fugit voluptas dolorem molestiae id at quidem adipisci neque officia asperiores ad fuga reprehenderit porro in eaque eveniet officiis optio quos! Soluta, iusto explicabo. Distinctio neque quia non omnis ipsum praesentium beatae quidem ab! Enim est sapiente voluptas eum libero architecto quos? Nam, exercitationem sit temporibus culpa sed praesentium numquam fugit ut dicta odit soluta? Omnis rerum, iusto tempore nemo sapiente in ad sit eum nobis quia fugit? Placeat atque quo provident, molestias quia vero consectetur, quaerat accusamus ipsam consequatur similique maiores incidunt et laboriosam vel numquam hic fugiat eveniet veniam tempora.", "Trung Quốc", 75, 2002, "Hành động", "assets/images/product-all/DauPhaThuongKhung1.jpg", 26000));

            Application["listMovie"] = movies;

            //đếm số người đang truy cập website
            Application["counter"] = 0; //gán số lượt truy cập bằng 0

            //đăng nhập quá 3 lần thì bị lock
            Application["lock"] = 0;
        }

        protected void Session_Start(object sender, EventArgs e)
        {
            Session.Timeout = 1;
            //kiểm tra xem có bằng null không
            if(Application["counter"] != null)
            {
                Application.Lock();//khóa application lại đề phòng khi nhiều user cùng đăng nhập sẽ xử lý không chính xác
                int i = int.Parse(Application["counter"].ToString()); //=> gán i bằng số lượt truy cập
                Application["counter"] = ++i; //gán lại cho số lượt truy cập bằng ++i
                Application.UnLock();
            }

            Session["userLogin"] = new user();



        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {

        }

        protected void Application_AuthenticateRequest(object sender, EventArgs e)
        {

        }

        protected void Application_Error(object sender, EventArgs e)
        {

        }

        protected void Session_End(object sender, EventArgs e)
        {
            //tương tự khi mà 1 người kết thúc phiên làm việc thì phải giảm 1
            if (Application["counter"] != null)
            {
                Application.Lock();//khóa application lại đề phòng khi nhiều user cùng đăng nhập sẽ xử lý không chính xác
                int i = int.Parse(Application["counter"].ToString()); //=> gán i bằng số lượt truy cập
                Application["counter"] = --i; //gán lại cho số lượt truy cập bằng ++i
                Application.UnLock();
            }
        }

        protected void Application_End(object sender, EventArgs e)
        {

        }
    }
}